import jsPDF from 'jspdf';
import type { MatchResult } from '../types';

export async function exportReportAsPdf(
  result: MatchResult,
  selectedSymptoms: string[]
) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const darkTextColor = [30, 41, 59];

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('AI Doctor Simulator - Educational Pattern Report', 14, 14);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('8th Standard National Science Fair Demonstration | Machine Learning Analytics', 14, 22);

  // Disclaimer Box
  doc.setFillColor(254, 243, 199);
  doc.setDrawColor(245, 158, 11);
  doc.rect(14, 34, 182, 22, 'FD');

  doc.setTextColor(146, 64, 14);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('⚠️ STRICT EDUCATIONAL DISCLAIMER ONLY', 18, 41);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(
    'This report is generated by a computer simulation comparing fictional training examples.',
    18,
    47
  );
  doc.text(
    'It does NOT constitute a medical diagnosis. Always consult certified healthcare professionals.',
    18,
    52
  );

  // Prediction Section
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('1. Machine Learning Prediction Output', 14, 66);

  doc.setFontSize(11);
  doc.text(`Predicted Pattern Category: ${result.category}`, 14, 74);
  doc.text(`Mathematical Confidence Score: ${result.confidence}%`, 14, 81);

  // Symptoms Tested
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Active Fictional Symptoms Tested:', 14, 91);
  doc.setFont('helvetica', 'normal');
  const symptomListText =
    selectedSymptoms.length > 0
      ? selectedSymptoms.join(', ')
      : 'None (Healthy Control Baseline Record)';
  doc.text(doc.splitTextToSize(symptomListText, 180), 14, 97);

  // Transparent Reasoning
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('2. How the AI Calculated This Pattern', 14, 112);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  let yPos = 120;
  result.reasonBullets.forEach((bullet) => {
    const lines = doc.splitTextToSize(`• ${bullet}`, 180);
    doc.text(lines, 14, yPos);
    yPos += lines.length * 6;
  });

  // Top-3 Similar Fictional Cases
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('3. Nearest Fictional Training Vectors (KNN Match)', 14, yPos + 6);

  yPos += 14;
  result.topSimilarCases.forEach((c, idx) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.text(
      `Case ${idx + 1}: ${c.caseCode} | Category: ${c.category} | ${c.similarityPercent}% Similarity`,
      14,
      yPos
    );
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.text(`Recorded Symptoms: ${c.symptoms.join(', ') || 'None'}`, 18, yPos + 5);
    yPos += 12;
  });

  // Footer Note
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated on ${new Date().toLocaleDateString()} at National Science Exhibition &bull; AI Doctor Simulator`,
    14,
    285
  );

  doc.save(`AI_Doctor_Simulator_Report_${result.category.replace(/\s+/g, '_')}.pdf`);
}
